language: r
fortran: false
latex: false

matrix:
  include:
    - r: oldrel
      brew_packages: yajl # only to test for conflicts
jobs:
  include:
    #- name: r-3.5
    #  env: R_VERSION="3.5"
    - name: r-4.0
      env: R_VERSION="4.0"
