---
title: "sp2000 - R Package to download online database of the Chinese known species of animals, plants, fungi and micro-organisms"
output: github_document
---

### Install rasterSp package

To *use* the package, you first have to install it from GitHub using the `remotes` package. 

```{r, install_package, eval=FALSE}
# Install dependence packages
packages <- c("jsonlite", "tibble","parallel","purrr","rlist")
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE, repos = "http://cran.us.r-project.org")
    library(x, character.only = TRUE)
  }
})
# Install remotes if not previously installed
if(!"remotes" %in% installed.packages()[,"Package"]) install.packages("remotes")
# Install rasterSp from Github if not previously installed
if(!"sp2000" %in% installed.packages()[,"Package"]) remotes::install_github("Otoliths/sp2000")
```


Load the sp2000 package

```{r}
library(sp2000)
```


### examples


```{r , eval=F}
#download taxon IDs via familyID ,scientificName and commonName
taxonID(query="鳗鲡",name="commonName",apiKey="")
query <- c("鳗鲡","裂腹鱼")
taxonIDs <- lapply(query,taxonID,name='commonName')
(taxonIDs <- purrr::transpose(taxonIDs))

#download detailed lists via species or infraspecies ID
x1 <- sp2000(query="025397f9-9891-40a7-b90b-5a61f9c7b597",apiKey=" ")
query <- c("025397f9-9891-40a7-b90b-5a61f9c7b597","04c59ee8-4b48-4095-be0d-663485463f21","4c539380-8d0a-4cbf-b612-1e6df5850295","522c1cfd-0d2c-490f-b8f8-0c7459f6dba5","6d04dcf5-f390-472d-b674-4f09e43713ed","89c29448-a48f-46cb-a573-ee51dd47e7b0","a3452c0c-6d75-465b-b110-537e4ac15f80","a69df232-07e4-4f06-9651-a4e52796f01a","b8c6a086-3d28-4876-8e8a-ca96e667768d","c1dbe9f7-e02f-4f05-a1ca-1487a41075bd","d5938c75-e51a-4737-aaef-4f342fa8b364","f95f766f-7b96-464a-bff5-43b1adafcf50","faaf346f-49f4-400a-947b-edb6b0f6bd5e")
x2 <- sp2000(query=query,apiKey=" ")

#lists convert data frame
x3 <- listdf(x2)
```


